version: "3.9"
services:
  #
  # ArduPilot SITL simulator (this image)
  #
  sitl:
    image: sitin/ardupilot-sitl:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARDUPILOT_TAG
        - USER=ardupilot
    # Example additional parameters.
    command:
      - --mavlink-gimbal
    # When these variables are set, SITL runner will create
    # the corresponding arguments for `sim_vehicle.py`.
    environment:
      # Vehicle config
      - INSTANCE
      - VEHICLE
      - FRAME
      - LOCATION
      - SPEEDUP
      # Custom location
      - LATITUDE
      - LONGITUDE
      - ALTITUDE
      - DIRECTION
      # General config
      - USE_DIR
      - NO_WIPE_EEPROM
      - SILENT_START
      # X11
      - DISPLAY
    ports:
      - "${SITL_MAVLINK_PORT}:5760"
    volumes:
      - ./sitl-start.sh:/ardupilot/sitl-start.sh
      - ./.volumes/ardupilot/state:/home/ardupilot/.state
    env_file:
      - .env
  #
  # MAVProxy
  #   Startup options: https://ardupilot.org/mavproxy/docs/getting_started/starting.html
  #
  # Connects to SITL and proxies UDP to `MAV_PROXY_PORT` (14550 by default)
  mavproxy:
    image: sitin/mavproxy:latest
    stdin_open: true
    tty: true
    entrypoint:
      - run-mavproxy
    command:
      - --master=tcp:sitl:5760
      - "--out=udp:host.docker.internal:${MAV_PROXY_UDP_PORT}"
      - --map
      - --console
    environment:
      - DISPLAY
    env_file:
      - .env
    volumes:
      - ./.volumes/mavproxy/logs:/var/log/mavproxy
      - ./.volumes/mavproxy/state:/mavproxy
    depends_on:
      - sitl
